config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'static_pages#index'
  
  get 'static_pages/index'
 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    belongs_to :attendee, class_name: "User"
    belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
    validates :start_date, :duration, :title, :description, :price, :location, presence: true
    validates :title, length: {in: 5..140}
    validates :description, length: {in: 20..1000}
    validates :price, numericality: {only_integer: true, greater_than: 0}
    validate :start_after_now, :validate_duration, on: :create

    belongs_to :admin, class_name: "User"
    has_many :attendances
    has_many :attendees, class_name: "User", through: :attendances

    def start_after_now
        if start_date.present? && start_date < Date.today
            errors.add(:start_date, "un évenement ne peut pas être dans le passé")
        end
    end

    def validate_duration
        if (duration.present?) && ((duration.to_i < 0) || (duration.to_i % 5 != 0))
            errors.add(:duration, 'la durée doit être supérieure à 0 et par tranche de 5minutes')
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    after_create :welcome_send

    validates :email, :first_name, :last_name, presence: true
    
    has_many :attend_events, foreign_key: 'attendee_id', class_name: "Attendance"
    has_many :admin_events, foreign_key: 'admin_id', class_name: 'Event'

    def welcome_send
        UserMailer.welcome_email(self).deliver_now
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def index
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body>
  <body class="justify-content-center">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= root_path %>">Eventbrite</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="<%= #static_pages_path %>">Team</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= #new_static_page_path %>">Contact</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= gossips_path %>">Gossips</a>
      </li>
      <a class="nav-link" href="<%= new_user_path %>">S'inscrire</a>
      </li>
      <a class="nav-link" href="<%= new_session_path %>">Login</a>
      </li>
    </ul>
  </div>
</nav>
<div class="container justify-content-center text-center" style="padding-top: 3rem">
    <%= yield %>
</div>
    <%= yield %>
  </body>
</html>